### ISSUE TITLE
minimize doesnt work

### ISSUE THREAD

**Issue by Nevu** [codearrows/sketch-focus#6]
Hello Guys!

Very very nice plugin. I use it very often and love it. But I think I found a bug. When I try to minimize the window (via green button), the minimizing seems not to work correctly. The windo doesnt minimize, just a part of content. I will attach pictures of it. Could you fix it?

<img width="319" alt="min" src="https://user-images.githubusercontent.com/2456068/29413799-f2d2a6ec-835d-11e7-9d81-99f00ea9edaa.png">
<img width="325" alt="full" src="https://user-images.githubusercontent.com/2456068/29413798-f2d23acc-835d-11e7-9d68-c0d13bb0e053.png">

**Comment by lukasondrej** [comment]
Hi @Nevu, sorry for a delayed response. This behaviour is actually intentional because it allows you to see more content, e.g. notes and tasks, at once. There's no need to truly minimize the window because it'd be the same as just closing and reopening it since the plugin keeps running in the background. Hope that makes sense.
