### ISSUE TITLE
Sketch Focus does no appear after clicking Plugins/Sketch Focus

### ISSUE THREAD

**Issue by Onlineheld** [codearrows/sketch-focus#7]
Every time I go to Plugins -> Sketch Focus, nothing happens.
I already uninstalled it several times and installed it manually as well as via Sketch Toolbox 2.
(Sketch Version 46.2)

**Comment by parkerchard** [comment]
I'm experiencing the same issue even after uninstalling/reinstalling several times in Sketch Version 46.2

**Comment by lukasondrej** [comment]
@Onlineheld @parkerchard We've tested Sketch Focus 1.3.0 with Sketch 46.2 and it seems to work perfectly for us. There is a rare issue which can cause the window to not show up. Please follow the instructions in this video to easily fix it: https://youtu.be/f6vP52VsSTE

**Comment by parkerchard** [comment]
Thanks for your reply - still no window showing up after following the instructions in that video. When I search for Focus in the Prefs Editor I only see the SketchFocusSettings - no SketchFocusLicense or SketchFocusLicenseVerification. Could that have something to do with it? Also I'm using the trial version of Sketch 46.2.

**Comment by dnlswan** [comment]
I also don't seem to be getting focus to work on 46.2. No window shows.

**Comment by lukasondrej** [comment]
Sorry for getting back to this so late. We've tried all possible ways we could think of to reproduce this bug but the window always shows up for us. On possibility could be an issue with multi-monitor setup. Could this apply to you?

**Comment by parkerchard** [comment]
No worries and sorry to hear you're unable to reproduce the issue. I'm not using a multi-monitor setup at this time. I'm currently on a 15" Macbook Pro Retina Mid 2014 running macOS Sierra v10.12.6

**Comment by leadelazer** [comment]
This issue is still happening for me, running OS and sketch on latest versions on a MBP 15" Retina. Is this plugin still under development? It looks so promising and I would really like to use it.

**Comment by lukasondrej** [comment]
Sorry to hear that it still happens. We're working on a brand new version
of Focus which will be out soon.

On 9 Nov 2017 9:34 am, "Lea Delazer" <notifications@github.com> wrote:

This issue is still happening for me, running OS and sketch on latest
versions on a MBP 15" Retina. Is this plugin still under development? It
looks so promising and I would really like to use it.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/codearrows/sketch-focus/issues/7#issuecomment-343098716>,
or mute the thread

**Comment by leadelazer** [comment]
I managed to solve this with the preference edit fix, had to delete all settings also from Sketch Beta and restart my OS. Now the window appears! Excited to start working with focus ;)
